Repository fusionjs/fusion-plugin-react-redux, pull requests merged in 2018-10, with the labels that each got.

#164 Update dependencies
  package.json
  yarn.lock
Labels: greenkeeping

#166 Upgrade dependency versions
  package.json
  yarn.lock
Labels: greenkeeping

#169 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor

#172 Fix missing cleanup method in plugin's browser env definition
  src/__tests__/index.browser.js
  src/browser.js
Labels: bugfix

#173 Release v1.0.10
  package.json
Labels: release
