Repository fusionjs/fusion-plugin-react-redux, pull requests merged in 2019-03, with the labels that each got.

#195 Constrain react-redux to <6
  package.json
Labels: bugfix

#196 Release v1.1.2-0
  package.json
Labels: release

#197 Release v1.1.2
  package.json
Labels: release

#198 Fix the import statement in EnhancerToken section
  README.md
Labels: docs
