Repository fusionjs/fusion-plugin-react-redux, pull requests merged in 2019-02, with the labels that each got.

#184 Upgrade flow and fix type test regression
  package.json
  src/tokens.js
  yarn.lock
Labels: bugfix, greenkeeping

#187 Release v1.1.1-1
  package.json
Labels: release

#191 Infer generic type T in GetInitialStateType<T> to prevent regressions in internal uber app
  src/tokens.js
Labels: bugfix

#192 Release v1.1.1-2
  package.json
Labels: release

#194 Release v1.1.1
  package.json
Labels: release
